#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0) uniform sampler2D inputImage;
layout (set = 1, binding = 1, rgba8) uniform image2D resultImage;

void main()
{   
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    vec2 textureCoords = vec2(pixelCoords.x / 1024.0, pixelCoords.y / 800.0);
    
    vec4 pixel = texture(inputImage, textureCoords);
                         
    imageStore(resultImage, pixelCoords, pixel);
}
